### ISSUE TITLE
Support for M5Stack CoreS3 ESP32S3

### ISSUE THREAD

**Issue by Roemotion** [project-sternbergia/cybergear_m5#13]
Hello,
Will this also support the M5Stack CoreS3 ESP32S3?
https://shop.m5stack.com/products/m5stack-cores3-esp32s3-lotdevelopment-kit
Thanks,
Brian

**Comment by chikuta** [comment]
Hello Brian,

Thank you for your inquiry. It seems that the M5Stack Commu module should be compatible with the M5Stack CoreS3 ESP32S3. The Commu module is designed to enhance communication capabilities and strengthen integration with the M5Stack series. Therefore, it is likely that it supports the M5Stack CoreS3 ESP32S3 as well.
