### ISSUE TITLE
[Bug] Speed control via bridge is not functioning properly

### ISSUE THREAD

**Issue by Haruki33086** [project-sternbergia/cybergear_m5#14]
### Describe the bug
When I sent commands from ROS 2 to control the speed, it became apparent that the motor was not behaving correctly. The motor would rotate slightly only when the speed was altered, but when the same speed value was applied, the motor would only oscillate and not rotate.

### To reproduce
1. Using [this repository](https://github.com/project-sternbergia/cybergear_m5), write a bridge for ROS communication to M5Stack.
2. Build [this repository](https://github.com/project-sternbergia/cybergear_m5_ros2) into the ROS environment and send speed commands to the motor for speed control.

### To resolve
There is a bug in `cybergear_bridge.cpp`. Originally, `send_speed_command` should be used to send speed commands, but `send_current_command` is used, and current values are being sent. Therefore, `send_current_command` should be replaced with `send_speed_command`.

### System Info
- M5Stack Gray
- CyberGear
- PC (Ubuntu 22.04, ROS 2 Humble)

**Comment by chikuta** [comment]
Thank you for the bug report. I will take a moment to review it promptly.

**Comment by chikuta** [comment]
OK, I understand your comment. I fixed this bug at #15.
I have resolved the issue you reported. Thank you for your assistance.

https://github.com/project-sternbergia/cybergear_m5/blob/615471a439eb71f69abf6e6d5420ed7d2de15a44/src/cybergear_bridge.cpp#L101-L108

**Comment by Haruki33086** [comment]
good job!
