### ISSUE TITLE
Each sample code is not displayed as an Example in the Arduino IDE.

### ISSUE THREAD

**Issue by robosithi** [project-sternbergia/cybergear_m5#18]
Thank you for the production.
Each Example is not recognized as a sample by the Arduino IDE because it is not in the folder with the same name.
This is not a fatal problem, but it would be appreciated if you could fix it.

**Comment by chikuta** [comment]
Thank you for your comment.
Just a moment. I'll fix it.

**Comment by chikuta** [comment]
@robosithi 
thank you your excellent issue. I fixed it.
