### ISSUE TITLE
always restart

### ISSUE THREAD

**Issue by qian-mo** [project-sternbergia/cybergear_m5#19]
Now I am using M5stack Basic V2.6. The communication uses the mcp2515 module. It keeps restarting after booting. What is the reason?

The log printed by the serial port is as follows:
`
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13964
load:0x40080400,len:3600
entry 0x400805f0
M5Stack initializing...
OK
Entering Configuration Mode Failure...
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400dad0a  PS      : 0x00060430  A0      : 0x800d2d2b  A1      : 0x3ffb2120  
A2      : 0xffffffff  A3      : 0x00000000  A4      : 0x98968000  A5      : 0x00000001  
A6      : 0xffffffff  A7      : 0x00000000  A8      : 0x000000ff  A9      : 0x00040000  
A10     : 0x00000007  A11     : 0xff000000  A12     : 0x00000015  A13     : 0x00000000  
A14     : 0x00060420  A15     : 0x00000001  SAR     : 0x0000000b  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x98968004  LBEG    : 0x40084929  LEND    : 0x40084931  LCOUNT  : 0x00000027  

Backtrace: 0x400dad07:0x3ffb2120 0x400d2d28:0x3ffb2140 0x400d21a6:0x3ffb2160 0x400d2945:0x3ffb2190 0x400d2a8a:0x3ffb21b0 0x400d2ac5:0x3ffb21d0 0x400d8f82:0x3ffb21f0 0x400d9074:0x3ffb2220 0x400d1dac:0x3ffb2240 0x400dbea9:0x3ffb2290

ELF file SHA256: d19d29a71b289377
`

**Comment by chikuta** [comment]
Hi @qian-mo .
Which module do you use ?  M5 commu module or others ?
In our repository, we recommend using the CommuModule. Additionally, we have not conducted debugging for any modules other than the CommuModule. If you are using a different module, what are the pin settings for the M5Stack you are using? Depending on the pins used, the M5Stack may experience repeated reboots.

**Comment by qian-mo** [comment]
I am not using the M5 commu module. I rewired the harness and updated the code, now it works fine. Thanks.

**Comment by chikuta** [comment]
Congratulations! Enjoy the development.
