### ISSUE TITLE
Unable to write RAM at some addresses

### ISSUE THREAD

**Issue by alvinsunyixiao** [project-sternbergia/cybergear_m5#23]
Have [these code](https://github.com/project-sternbergia/cybergear_m5/blob/46ded2351f9cec2a137dbf5cf234bfa93f77122d/src/cybergear_driver.cpp#L107-L120) been tested to work before? I am not able to programmatically write or read RAM for parameter address range 0x2000 - 0x2020.

**Comment by chikuta** [comment]
Sorry the address 0x20xx has not been tested. However, the address 0x70xx has been tested. Could it be that you're unable to write to it?

**Comment by alvinsunyixiao** [comment]
After some digging, I'm fairly certain that any address not in 0x70xx does not support reading or writing from the documented CAN protocols. However, the latest firmware seems to move those parameters into the 0x70xx range. See https://web.vip.miui.com/page/info/mio/mio/detail?postId=40233100

**Comment by chikuta** [comment]
Thank you your information. I'll imprement these address and ram damping functions.

![image](https://github.com/project-sternbergia/cybergear_m5/assets/948400/2d7b2289-adde-4324-9d89-8dba4253e529)

**Comment by chikuta** [comment]
@alvinsunyixiao 
I support fw 1.2.1.5 from #27. Thank you for your report !!
