### ISSUE TITLE
setting motor id is not working

### ISSUE THREAD

**Issue by wthierry** [project-sternbergia/cybergear_m5#31]
Ive tried several times, motor id never succeeds.

**Comment by chikuta** [comment]
Thank you for your feedback. Could you please describe the development environment you used, the source code you utilized, and how you executed it? 

If you're going to change the ID, I recommend using Xiaomi's official tool.

**Comment by wthierry** [comment]
I figured it out, it was me, apparently you are not supposed to run the commu controller with the m5stack base on the bottom.  I removed that, re-uploaded and was still having problems, but the dump data example did work....  It turns out that in my case, the m5stack core 2 only works with the CAN controller if I initialize the m5stack in the setup code with M5.begin(true, false, true);  none of the samples worked except for the data dump until I made this change...

**Comment by wthierry** [comment]
closed the issue, it was user error, but a learning opportunity.  Thanks
