### ISSUE TITLE
M5STACK.h not found

### ISSUE THREAD

**Issue by UsernameNotActive** [project-sternbergia/cybergear_m5#33]
I imported the four libraries. When I try running the example code, I get this error.

**Comment by chikuta** [comment]
Hi, I apologize, but I don’t have enough information to fully understand what environment you are using and what issues you are facing. Could you at least provide details on which development environment you’re using, which board you’re working with, and what you’re trying to achieve?

**Comment by UsernameNotActive** [comment]
When I try running the file, I get: 
Compilation error: cybergear_bridge.hh: No such file or directory
The same error occurs for the M5_stack library as well.
I tried running using Arduino IDE and PlatformIO (visual studio code extension). 
I tried deleted and reimporting the libraries, using Arduino IDE imports, and import through terminal. I don't know what the problem could be.

my File path:
Arduino
 |______Cybergear_m5-main
 |         |______examples
 |                    |______control_mode_example
 |                              |_____control_mode_example.ino
 |______Libraries
           |______cybergear_m5
           |______M5Stack
           |______etc..
